export const actionTypes = {
  SET_MICROPHONE_STATUS: "SET_MICROPHONE_STATUS",
  SET_SERVER_STATUS: "SET_SERVER_STATUS",
  SELECT_ITEM: "SELECT_ITEM",
  SELECT_EXTRA_ITEM: "SELECT_EXTRA_ITEM",
  SET_ACTIVE: "SET_ACTIVE",
  SET_SPINNER: "SET_SPINNER",
  SET_METHODS: "SET_METHODS",
  SET_DEVICE: "SET_DEVICE",
  TOGGLE_TOAST: "TOGGLE_TOAST",
  SET_STATUS: "SET_STATUS",
  SET_TONE: "SET_TONE",
};
